// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5AVugo6tj0tyGtiLgyaUWtFUg0iqjRto',
    appId: '1:371537109549:web:a7609fcb205395ecf70ea4',
    messagingSenderId: '371537109549',
    projectId: 'poc-firebase-and-postgres',
    authDomain: 'poc-firebase-and-postgres.firebaseapp.com',
    storageBucket: 'poc-firebase-and-postgres.firebasestorage.app',
    measurementId: 'G-XHQ167V72W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdUvbtNkuTYnXncqik9CVhZgVuZHoiAM',
    appId: '1:371537109549:android:36df25731b52b6a9f70ea4',
    messagingSenderId: '371537109549',
    projectId: 'poc-firebase-and-postgres',
    storageBucket: 'poc-firebase-and-postgres.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZwGip6y7kB4y1N6gGeCgXQyIyIwXmA8',
    appId: '1:371537109549:ios:f356163eddb0018cf70ea4',
    messagingSenderId: '371537109549',
    projectId: 'poc-firebase-and-postgres',
    storageBucket: 'poc-firebase-and-postgres.firebasestorage.app',
    iosBundleId: 'com.example.pocFirebaseAndPostgres',
  );
}
